# Generated by Django 5.0.3 on 2024-03-09 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recipe_author_alter_recipe_ingredients_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='who_cart', to='api.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoritedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favorited', to='api.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favorited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
