# Generated by Django 5.0.3 on 2024-03-16 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_cart', to='api.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='favoritedrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited', to='api.recipe', verbose_name='Рецепт'),
        ),
    ]
