version: '3'

volumes:
  pg_data:
  media:
  static:

services:
  
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: qrugma/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: qrugma/foodgram_frontend
    command: cp -r /app/build/. /static
    volumes:
      - static:/static

  nginx:
    image: qrugma/foodgram_gateway
    ports:
      - 8080:80
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
