version: '3'

volumes:
  pg_data:
  media:
  static:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend
