# Generated by Django 5.0.3 on 2024-03-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_related_name': 'recipes', 'ordering': ['name'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'рецепты'},
        ),
    ]
