# Generated by Django 5.0.3 on 2024-03-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_follow_unique_together_follow_unique_follower_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name="can't_sub_on_self",
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('follower')), _negated=True), name='cannot_sub_on_self'),
        ),
        migrations.AddConstraint(
            model_name='myuser',
            constraint=models.CheckConstraint(check=models.Q(('username', 'me'), _negated=True), name='username_cannot_be_me'),
        ),
    ]
