# Generated by Django 5.0.3 on 2024-03-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240306_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritedrecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='favoritedrecipe',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='FavoritedRecipe',
        ),
    ]
