# Generated by Django 3.2.16 on 2024-03-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_follow_follower'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_following',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'follower')},
        ),
    ]
