# Generated by Django 5.0.3 on 2024-03-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_follow_follower_alter_follow_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'подписчики'},
        ),
    ]
